title: Quiet Current
description: "흐름에 몸을 싣고, 나를 단련하다"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
timezone: Asia/Seoul
lang: ko
permalink: /:categories/:year/:month/:day/:title/
url: https://kt-kang.github.io
baseurl: ""
toc:
  enabled: true
  h_min: 1
  h_max: 3
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
collections:
  pages:
    output: true
    permalink: /:collection/:path/
ordered_collections:
  - pages
  - posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "main"
exclude:
  - _site
  - .bundle
  - .jekyll-cache
  - vendor
  - node_modules
  - private
