title: 운동과 투자일지
description: 운동 기록과 투자 생각을 담는 개인 블로그
remote_theme: sighingnow/jekyll-gitbook
timezone: Asia/Seoul
lang: ko
author: Kyoungtae
permalink: /:categories/:year/:month/:day/:title/
url: https://kt-kang.github.io
baseurl: ""
toc:
  enabled: true
  h_min: 1
  h_max: 3
plugins:
  - jekyll-remote-theme
collections:
  pages:
    output: true
    permalink: /:collection/:path/
ordered_collections:
  - pages
  - posts
